# curl --location --request GET 'http://localhost:6622/sulama/api/user'
#--header 'Authorization:'
GET http://localhost:6622/sulama/api/user
Authorization: {{token}}

###

# curl --location --request GET 'http://localhost:6622/sulama/api/user/2'
#--header 'Authorization:'
GET http://localhost:6622/sulama/api/user/3
Authorization: {{token}}

###

# curl --location --request GET 'http://localhost:6622/sulama/api/user/all'
#--header 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY2MjIwMzU4MywiaWF0IjoxNjYyMTg1NTgzfQ.FlYQG4u9o-bo7u2yS18_2QE5i-xTe1wx5hBK7b9Qv5-Ew83eern9D9mOK1iKNNKh0h-lc-nAThZPMRtC-fH1gA'
GET http://localhost:6622/sulama/api/user/all
Authorization: {{token}}

###

# curl --location --request POST 'http://localhost:6622/sulama/api/user/changePassword'
#--header 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY2MjI1Mzc0MSwiaWF0IjoxNjYyMjM1NzQxfQ.GpOQ2i-Tl6VvjF_epVhwO6OETzClhkr5M_OLT5lWNX2L1lMZSuEABj8di6GC6jf-4bJ5mEQ6DZRQxaeT4w4TJg'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "password":"test!4252E",
#    "passwordConfirm":"test!4252E"
#}'
POST {{host}}/sulama/api/user/changePassword
Authorization: {{token}}
Content-Type: application/json

{
  "password":"test!4252E",
  "passwordConfirm":"test!4252E"
}

###

# curl --location --request POST 'http://localhost:6622/sulama/api/user'
#--header 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY2MjI1Mzc0MSwiaWF0IjoxNjYyMjM1NzQxfQ.GpOQ2i-Tl6VvjF_epVhwO6OETzClhkr5M_OLT5lWNX2L1lMZSuEABj8di6GC6jf-4bJ5mEQ6DZRQxaeT4w4TJg'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "name": "test bahaa",
#    "surname": "",
#    "username": "mustafa",
#    "password": "test!4252E",
#    "enabled": true,
#    "admin": true
#}'
# for update you just added "id" property to the body
POST {{host}}/sulama/api/user
Authorization: {{token}}
Content-Type: application/json

{
  "name": "test bahaa",
  "surname": "",
  "username": "mustafa",
  "password": "test!4252E",
  "enabled": true,
  "admin": true
}

###
