project:
  name: Sulama Service
  description: API Application
  appTag: sulamaMainService
  mainPath: /sulama/

spring:
  application:
    name: sulama-service
  jpa:
    open-in-view: true
    database: POSTGRESQL
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://206.81.17.83:5432/sulama?characterEncoding=UTF-8
    username: sulamaadmin
    password: 21373582
    initialization-mode: never
    driverClassName: org.postgresql.Driver
    tomcat:
      connection-properties: characterEncoding=utf-8;
    hikari:
      data-source-properties:
        characterEncoding: UTF-8
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

logging:
  level:
    root: WARN
    org:
    springframework: ERROR


# ===============================
# = SERVER
# ===============================
server:
  port: 6622
  servlet:
    context-path: /sulama

# ===============================
# = SECURITY
# ===============================
security:
  jwt:
    secret: tmo3Wtfs!


tcp-socket:
  port: 6623
  heartbeat:
    timeout: 6000
  client-test:
    state: false
    number: 5
